### ISSUE TITLE
Should be ported to the newest Version, 4.0.0

### ISSUE THREAD

**Issue by kjellski** [MvvmCross/MvvmCross-Tutorials#18]
Right now the examples are not really usable because all references are broken for the latest release. Should we go ahead and try to port it to 4.0.0.0?

**Comment by martijn00** [comment]
Most of them are ported to the new samples repo: https://github.com/MvvmCross/MvvmCross-Samples

There's a folder in there called OldSamples, which still need to be updated to 4.0. We would be pleased to take in Pull requests to fix that!

**Comment by chanti-github** [comment]
Hi martijn00 ,
Could you please provide link or  full example for integration of maps with mvvmcross 4.0 version.

**Comment by martijn00** [comment]
@chanti-github Please open a new issue in the Samples repo.
