### ISSUE TITLE
MvvmCross-Tutorials/QuickLayout/ is outdated from Cirrious.FluentLayout

### ISSUE THREAD

**Issue by flyingxu** [MvvmCross/MvvmCross-Tutorials#20]
The project of MvvmCross-Tutorials/QuickLayout/ is outdated and there seems to be an upstream project of Cirrious.FluentLayout (https://github.com/FluentLayout/Cirrious.FluentLayout) which is more updated but in a different repo.

I think there are 2 options to make QuickLayout project updated:

1. Hard copy all the files from Cirrious.FluentLayout (https://github.com/FluentLayout/Cirrious.FluentLayout) and commit the change
2. Delete QuickLayout folder and add a submodule to Cirrious.FluentLayout (https://github.com/FluentLayout/Cirrious.FluentLayout)

I'd like to seek some comment then I'd like to create a PR.

**Comment by martijn00** [comment]
It's even more easier. You can delete all old references and just add a nuget to the new Cirrious.FluentLayout package. It would be good to have a PR for that!
